password_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('passwords.urls', namespace='passwords')),
    path('platforms/', include('platforms.urls', namespace='platforms')),
    path('masters/', include('masters.urls', namespace='masters')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

platforms/urls.py
from django.urls import path
from .views import PlatformCreateView, PlatformLitView, PlatformUpdateView, PlatformDetailView, PlatformConfirmDeleteView

app_name = "platforms"
urlpatterns = [
    path('create/', PlatformCreateView.as_view(), name='create'),
    path('list/', PlatformLitView.as_view(), name='list'),
    path('list/', PlatformLitView.as_view(), name='list'),
    path('<int:pk>/update/', PlatformUpdateView.as_view(), name='update'),
    path('<int:pk>/detail/', PlatformDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', PlatformConfirmDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.urls import path
from .views import SignUpView

app_name='users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

platforms/models.py
from django.db import models
from django.conf import settings
from django.db.models.query_utils import select_related_descend
from django.urls import reverse

User = settings.AUTH_USER_MODEL


class Platform(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField()
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('platforms:detail', kwargs={'pk': self.pk})

    def get_absolute_update_url(self):
        return reverse('platforms:update', kwargs={'pk': self.pk})

    def get_absolute_delete_url(self):
        return reverse('platforms:delete', kwargs={'pk': self.pk})

platforms/forms.py
from django import forms
from .models import Platform

class PlatformForm(forms.ModelForm):
    class Meta:
        model = Platform
        fields = ['name', 'url', 'description']
        
        

platforms/views.py
from django.shortcuts import render
from django.urls.base import reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.views.generic.edit import DeleteView
from .models import Platform
from .forms import PlatformForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

class PlatformCreateView(LoginRequiredMixin, CreateView):
    form_class = PlatformForm
    model = Platform
    template_name ='platforms/platform_form.html'
    
    def get_success_url(self) -> str:
        return reverse("platforms:list")
class PlatformUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PlatformForm
    model = Platform
    template_name ='platforms/platform_form.html'

    def get_success_url(self) -> str:
        return reverse("platforms:list")

class PlatformLitView(LoginRequiredMixin, ListView):
    model = Platform


class PlatformDetailView(LoginRequiredMixin, DetailView):
    model = Platform
    
class PlatformConfirmDeleteView(LoginRequiredMixin, DeleteView):
    model = Platform
    
    def get_success_url(self) -> str:
        return reverse("platforms:list")

platforms/templates/platforms/platform_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-8 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h2 class="text-center">
                        Are you sure want to delete {{platform.name}} ?
                    </h2>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="text-right">
                            <input type="submit" value="Delete" class="btn btn-sm btn-danger">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

platforms/templates/platforms/platform_detail.html
{% extends 'base.html' %}



{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-8 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h2 class="text-center text-primary"> {{platform.name}} </h2>
                    <p> {{platform.description}} </p>
                </div>
                <div class="card-footer">
                    <div class="text-right">
                        <a  class="btn btn-warning" href="{{platform.get_absolute_update_url}}">Edit</a>
                        <a class="btn btn-danger" href="{{platform.get_absolute_delete_url}}">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

platforms/templates/platforms/platform_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-8 mx-auto">
            <div class="card">
                <h2 class="text-primary text-center">Create a Platform</h2>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class="text-right">
                            {% if platform %}
                            <button type="submit" class="btn btn-sm btn-success">Update</button>
                            {% else %}
                            <button type="submit" class="btn btn-sm btn-success">Create</button>
                            {% endif %}

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

platforms/templates/platforms/platform_list.html
{% extends 'base.html' %}



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8 mx-auto">
            <h2 class="text-center">Platform List</h2>
            <table class="table mt-5">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Platform</th>
                        <th scope="col">Description</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for platform in platform_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td> <a href="{{ platform.get_absolute_url }}"> {{ platform.name }}</a> </td>
                        <td>{{ platform.description }}</td>
                        <td>
                            <a href="{{ platform.get_absolute_update_url }}" class="btn btn-warning btn-sm">
                                Edit
                            </a>
                        </td>
                        <td>
                            <a href="{{platform.get_absolute_delete_url}}" class="btn btn-danger btn-sm">
                                Delete
                            </a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            <div class="text-right mt-5">
                <a class="btn btn-success btn-sm" href="{% url 'platforms:create' %}">Create a new Platform</a>
            </div>

        </div>
    </div>
</div>
{% endblock content %}