password_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('passwords.urls', namespace='passwords')),
    path('platforms/', include('platforms.urls', namespace='platforms')),
    path('masters/', include('masters.urls', namespace='masters')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

passwords/urls.py
from django.urls import path

from .views import (
    PasswordListView,
    PlatformPasswordCreateView,
    PlatformDetailView,
    PlatformPasswordUpdateView,
    PlatformPasswordDeleteView,
)

app_name = 'passwords'
urlpatterns = [
    path('', PasswordListView.as_view(), name='list'),
    path('create/', PlatformPasswordCreateView.as_view(), name='create'),
    path('<int:pk>/update/', PlatformPasswordUpdateView.as_view(), name='update'),
    path('<int:pk>/detail/', PlatformDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', PlatformPasswordDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.urls import path
from .views import SignUpView

app_name='users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

templates/base/css.html
{% load static %}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

templates/base/footer.html
{% load static %}

templates/base/js.html
<!-- JS, Popper.js, and jQuery -->
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

templates/base/messages.html
    <div class="col-12 col-md-6 col-lg-4 ml-auto">
        {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{% if message.tags %}{{ message.tags }} {% endif %}  position-fixed alert-dismissible fade show"
               role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
        {% endfor %}
        {% endif %}
    </div>

templates/base/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Password Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'passwords:list' %}">Password List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'platforms:list' %}">Platforms</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'logout' %}">Logout </a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'login' %}">Sign In </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
            </li>
            {% endif %}

        </ul>
    </div>

</nav>